from .main_window_delegate import MainWindowDelegate
from .main_menu_bar_delegate import MainMenuBarDelegate
from .central_widget_delegate import CentralWidgetDelegate
from .document_tree_delegate import DocumentTreeDelegate